apiVersion: v1
kind: ConfigMap
metadata:
  name: cfg-clase
  namespace: dev
  labels:
    app: cfg-clase
data:
  PUERTO: "8080"
  DATABASE_URL: "jdbc:mysql://10.123.0.34:3306/clase"
  D1ATABASE_USER: "mauricio"
  D2ATABASE_PASS: "dfasdfadsf"
  TRM: "4005"


