apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-clase
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium-retain  
  resources:
    requests:
      storage: 3Gi
---
