apiVersion: v1
kind: Secret
metadata:
  name: sec-clase
  namespace: dev
  labels: 
    app: clase
stringData:
  PASSWORD_DB: "lunes"
--.
apiVersion: v1
kind: Secret
metadata:
  name: sec-clase
  namespace: dev
  labels: 
    app: clase
  type: Opaque
Data:
  PASSWORD_DB: "aG9sYQ=="
